### ISSUE TITLE
hi, what description for extension index?

### ISSUE THREAD

**Issue by ClashSAN** [guzuligo/CFG-Schedule-for-Automatic1111-SD#2]
@guzuligo, hi, do you have a description you want for the scripts?

Do you have some presets that work well?
Users may not know how to use it.

**Comment by guzuligo** [comment]
Hello @ClashSAN 
For the description, probably 
"This script allows for dynamic CFG control during generation steps. With the right settings, this could help get the details of high CFG without damaging the generated image even with low denoising in img2img."

For presets and how to use, I made some description of the CFG Schedule. Probably not enough, so I guess I'll have to start working on the Wiki.

I've actually made the CFG Auto script to make it easier without the mathy stuff on the schedule one, but only made two options.

**Comment by ClashSAN** [comment]
thanks. do what you can with describing in the readme as users may not know how to use. nice work.
